[book]
authors = ["nonedotone"]
language = "en"
multilingual = false
src = "src"
title = "Deployment"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
site-url = "/notes/deployment/"
git-repository-url = "https://github.com/nonedotone/notes/tree/master/deployment"
edit-url-template = "https://github.com/nonedotone/notes/edit/master/deployment/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2